### ISSUE TITLE
nifi-registry support git branch in values.yaml

### ISSUE THREAD

**Issue by chwongeric** [dysnix/charts#131]
Dear nifi-registry chart support,

Could we add git `branch` support for nifi-registry's `values.yaml`?
 I tried to add branch name like - `branch: 'develop'` but no luck, all flow files always write to `master `branch instead. How do I use and integrate with specific branch with nifi-registry in values.yaml?  

thanks a lot for help!

```
flowProvider:
  git:
    enabled: true
    url: 'https://user:passwd@bitbucket.org/developers/nifi_flows'
    remote: 'origin'
    branch: 'develop'
    user: 'user'
    password: 'passwd'

```
