### ISSUE TITLE
nifi-registry helm chart : flowPersistenceProvider not set to DatabaseFlowPersistenceProvider

### ISSUE THREAD

**Issue by stephbat** [dysnix/charts#252]
Hello

I'm using the helm chart nifi-registry version 1.1.4, and it seems that when I deploy it with the following custom values, the flowPersistenceProvider in the file conf/providers.xml, is not set to org.apache.nifi.registry.provider.flow.DatabaseFlowPersistenceProvider, but to the default value  org.apache.nifi.registry.provider.flow.FileSystemFlowPersistenceProvider

```
flowProvider:
  postgres:
    driverClass: org.postgresql.Driver
    driverURL: https://jdbc.postgresql.org/download/
    enabled: true
    fileName: postgresql-42.2.6.jar
    password: ******
    url: jdbc:postgresql://postgresql/nifiregistry
    username: *****
 persistence:
  enabled: false
 ````
 
I think that it's related to the bash script /opt/nifi-registry/scripts/update_flow_provider.sh, that takes into account the env variable NIFI_REGISTRY_FLOW_PROVIDER and the possible values git, file, database. In my case the env variable NIFI_REGISTRY_FLOW_PROVIDER is set to **postgres** and not to **database**

Thanks in advance for your help
