### ISSUE TITLE
Feature Request: Configure OIDC redirect URI

### ISSUE THREAD

**Issue by tjcsilicon** [dysnix/charts#314]
Hello,

This is my nifi registry config:

```
image:
  tag: "1.24.0"

service:
  type: ClusterIP
  port: 18443

certManager:
  enabled: true
  replaceDefaultTrustStore: true
  caDuration: 175320h
  caSecrets:
  - nifi-registry-ca # ca for nifi-registry
  - myca-secret # ca for traefik.local

ingress:
  enabled: true
  hosts:
    - host: traefik.local
      paths:
        - path: /nifi-registry
          pathType: Prefix
  annotations:
    kubernetes.io/ingress.ingressClassName: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/service.serversscheme: "https"

  tls:
    - hosts:
      - traefik.local
      secretName: traefik-tls    

security:
  enabled: true
  needClientAuth: false
  httpsHost: "0.0.0.0"
  httpsPort: 18443
  admin: "First Last"

persistence:
  enabled: true
  storageClass: "microk8s-hostpath"

oidc:
  enabled: true
  discoveryUrl: https://traefik.local/keycloak/realms/nifi/.well-known/openid-configuration
  clientId: nifi-registry
  clientSecret: 8s0N1IcHRlIiYhJaw9vxIoaTaTHblyPS
  admin: "First Last"
  claimIdentifyingUser: name
```

When connecting to the registry:
https://traefik.local/nifi-registry

My issues and requests:
1. It does not immediately redirect to keycloak for auth
2. It always says invalid redirect URI. However when looking at the browser search bar, the redirect url is the traefik proxy's pod name instead of the proxy path https://traefik.local:443/keycloak

Im not sure what @wknickless did on the cetic/helm-nifi chart to set the redirect url but the oidc configuration on cetic's chart works.
