### ISSUE TITLE
Monitoring port in StatefulSet

### ISSUE THREAD

**Issue by dbth21** [dysnix/charts#62]
svc-monitoring.yaml creates Kubernetes service with `targetPort: monitoring`:
```
  ports:
    - name: monitoring
      port: 6060
      targetPort: monitoring
```
But `monitoring` port is not defined in statefulset.yaml:
```
        ports:
        - name: rpc
          containerPort: {{ .Values.http.port }}
        - name: ws
          containerPort: {{ .Values.ws.port }}
```
Please add  "monitoring" port  in StatefulSet

Thank you
